repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files # Checks for file size limits
        args: ["--maxkb=5120"] # 5MB limit in KB

      - id: check-yaml # Ensures valid YAML format
      - id: end-of-file-fixer # Ensures file ends with a newline
      - id: trailing-whitespace # Removes trailing whitespace

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.55.2
    hooks:
      - id: golangci-lint # Enforces Go linting and formatting
        args: ["--fast"] # Runs a fast lint check

  - repo: https://github.com/mvdan/gofumpt
    rev: v0.5.0
    hooks:
      - id: gofumpt # Enforces stricter Go formatting rules

  - repo: https://github.com/uudashr/gocognit
    rev: v1.0.0
    hooks:
      - id: gocognit # Checks cyclomatic complexity in Go code

  - repo: https://github.com/dominikh/go-tools
    rev: 2023.1.2
    hooks:
      - id: staticcheck # Runs static analysis on Go code

  - repo: https://github.com/securego/gosec
    rev: v2.16.0
    hooks:
      - id: gosec # Checks for security vulnerabilities in Go code

  - repo: https://github.com/mgechev/revive
    rev: v1.3.1
    hooks:
      - id: revive # Linter with custom rules for Go

  - repo: https://github.com/golang/mock
    rev: v1.6.0
    hooks:
      - id: mockgen # Generates Go mocks for interfaces

  - repo: https://github.com/golang/tools
    rev: v0.12.0
    hooks:
      - id: goimports # Fixes import order and removes unused imports
